from __future__ import annotations

import csv
from pathlib import Path


CSV_HEADER = [
    "Date",
    "Start Time",
    "End Time",
    "Journey/Action",
    "Charge",
    "Credit",
    "Balance",
    "Note",
]


SAMPLE_FILES = {
    "999999999_20210318.csv": [
        [
            "12-Mar-2021",
            "07:41",
            "08:01",
            "Baker Street [London Underground] to Victoria [London Underground]",
            "2.40",
            "",
            "17.60",
            "",
        ],
        [
            "12-Mar-2021",
            "08:12",
            "08:27",
            "Victoria [London Underground] to Oxford Circus [London Underground]",
            "2.50",
            "",
            "15.10",
            "",
        ],
        ["12-Mar-2021", "18:05", "", "Bus journey, route 73", "1.55", "", "13.55", ""],
        [
            "12-Mar-2021",
            "18:37",
            "18:55",
            "Oxford Circus [London Underground] to Waterloo [London Underground]",
            "0.00",
            "",
            "13.55",
            "Daily cap applied",
        ],
        ["13-Mar-2021", "00:42", "", "Bus journey, route N5", "1.75", "", "11.80", ""],
        [
            "13-Mar-2021",
            "10:18",
            "",
            "Auto top-up",
            "",
            "20.00",
            "31.80",
            "Auto top-up",
        ],
        [
            "13-Mar-2021",
            "12:14",
            "12:33",
            "Waterloo (National Rail) to Stratford [National Rail]",
            "2.80",
            "",
            "29.00",
            "",
        ],
        [
            "13-Mar-2021",
            "13:02",
            "13:19",
            "Stratford [London Underground] to Green Park [London Underground]",
            "2.80",
            "",
            "26.20",
            "",
        ],
        [
            "15-Mar-2021",
            "07:56",
            "08:13",
            "Green Park [London Underground] to King's Cross St. Pancras [London Underground]",
            "2.60",
            "",
            "23.60",
            "",
        ],
        [
            "15-Mar-2021",
            "08:28",
            "08:41",
            "King's Cross St. Pancras [London Underground] to Euston [London Underground]",
            "0.00",
            "",
            "23.60",
            "Journey continuation",
        ],
        [
            "15-Mar-2021",
            "13:11",
            "",
            "Fare adjustment",
            "",
            "1.20",
            "24.80",
            "Fare adjustment",
        ],
        ["15-Mar-2021", "18:44", "", "Bus journey, route 205", "1.55", "", "23.25", ""],
        [
            "17-Mar-2021",
            "07:38",
            "07:56",
            "Euston [London Underground] to Paddington [London Underground]",
            "2.70",
            "",
            "20.55",
            "",
        ],
        [
            "17-Mar-2021",
            "08:09",
            "08:21",
            "Paddington [London Underground] to Baker Street [London Underground]",
            "2.40",
            "",
            "18.15",
            "",
        ],
        [
            "17-Mar-2021",
            "17:54",
            "18:12",
            "Baker Street [London Underground] to Holborn [London Underground]",
            "2.50",
            "",
            "15.65",
            "",
        ],
        ["17-Mar-2021", "23:11", "", "Bus journey, route N5", "1.75", "", "13.90", ""],
        [
            "18-Mar-2021",
            "08:03",
            "08:19",
            "Holborn [London Underground] to Bank [London Underground]",
            "2.50",
            "",
            "11.40",
            "",
        ],
        [
            "18-Mar-2021",
            "08:29",
            "08:46",
            "Bank [London Underground] to London Bridge [London Underground]",
            "2.40",
            "",
            "9.00",
            "",
        ],
        [
            "18-Mar-2021",
            "12:36",
            "",
            "Auto top-up",
            "",
            "10.00",
            "19.00",
            "Auto top-up",
        ],
        [
            "18-Mar-2021",
            "18:07",
            "18:25",
            "London Bridge [London Underground] to Canary Wharf [London Underground]",
            "2.60",
            "",
            "16.40",
            "",
        ],
    ],
    "999999999_20221020.csv": [
        [
            "14-Oct-2022",
            "07:58",
            "08:20",
            "King's Cross St. Pancras [London Underground] to Liverpool Street [London Underground]",
            "2.60",
            "",
            "24.40",
            "",
        ],
        [
            "14-Oct-2022",
            "08:24",
            "08:39",
            "Liverpool Street [London Underground] to Green Park [London Underground]",
            "0.00",
            "",
            "24.40",
            "Journey continuation",
        ],
        [
            "14-Oct-2022",
            "17:42",
            "18:01",
            "Green Park [London Underground] to Baker Street [London Underground]",
            "2.50",
            "",
            "21.90",
            "",
        ],
        ["14-Oct-2022", "18:18", "", "Bus journey, route 343", "1.55", "", "20.35", ""],
        ["15-Oct-2022", "00:46", "", "Bus journey, route N63", "1.75", "", "18.60", ""],
        [
            "15-Oct-2022",
            "10:30",
            "",
            "Auto top-up",
            "",
            "10.00",
            "28.60",
            "Auto top-up",
        ],
        [
            "15-Oct-2022",
            "12:14",
            "12:32",
            "Baker Street [London Underground] to Waterloo [London Underground]",
            "2.70",
            "",
            "25.90",
            "",
        ],
        [
            "15-Oct-2022",
            "12:46",
            "13:02",
            "Waterloo [London Underground] to London Bridge [London Underground]",
            "2.50",
            "",
            "23.40",
            "",
        ],
        [
            "17-Oct-2022",
            "07:43",
            "07:58",
            "London Bridge [London Underground] to Bank [London Underground]",
            "2.40",
            "",
            "21.00",
            "",
        ],
        ["17-Oct-2022", "08:15", "", "Bus journey, route 55", "1.55", "", "19.45", ""],
        [
            "17-Oct-2022",
            "12:03",
            "12:21",
            "Bank [London Underground] to Oxford Circus [London Underground]",
            "2.60",
            "",
            "16.85",
            "",
        ],
        [
            "17-Oct-2022",
            "18:07",
            "",
            "Fare adjustment",
            "",
            "1.25",
            "18.10",
            "Fare adjustment",
        ],
        [
            "18-Oct-2022",
            "07:50",
            "08:07",
            "Oxford Circus [London Underground] to Victoria [London Underground]",
            "2.40",
            "",
            "15.70",
            "",
        ],
        ["18-Oct-2022", "08:27", "", "Bus journey, route 168", "1.75", "", "13.95", ""],
        [
            "18-Oct-2022",
            "12:21",
            "12:36",
            "Victoria [London Underground] to South Kensington [London Underground]",
            "0.00",
            "",
            "13.95",
            "Daily cap applied",
        ],
        [
            "18-Oct-2022",
            "17:58",
            "18:16",
            "South Kensington [London Underground] to Paddington [London Underground]",
            "2.70",
            "",
            "11.25",
            "",
        ],
        [
            "20-Oct-2022",
            "08:04",
            "08:22",
            "Paddington [London Underground] to Euston [London Underground]",
            "2.70",
            "",
            "8.55",
            "",
        ],
        [
            "20-Oct-2022",
            "08:39",
            "08:52",
            "Euston [London Underground] to King's Cross St. Pancras [London Underground]",
            "2.40",
            "",
            "6.15",
            "",
        ],
        [
            "20-Oct-2022",
            "12:18",
            "",
            "Auto top-up",
            "",
            "15.00",
            "21.15",
            "Auto top-up",
        ],
        ["20-Oct-2022", "19:02", "", "Bus journey, route 15", "1.75", "", "19.40", ""],
    ],
    "999999999_20240411.csv": [
        [
            "05-Apr-2024",
            "07:51",
            "08:09",
            "Stratford [London Underground] to Oxford Circus [London Underground]",
            "2.80",
            "",
            "26.20",
            "",
        ],
        ["05-Apr-2024", "08:26", "", "Bus journey, route 73", "1.75", "", "24.45", ""],
        [
            "05-Apr-2024",
            "12:16",
            "12:34",
            "Oxford Circus [London Underground] to Victoria [London Underground]",
            "2.50",
            "",
            "21.95",
            "",
        ],
        [
            "05-Apr-2024",
            "12:48",
            "13:03",
            "Victoria [London Underground] to Waterloo [London Underground]",
            "0.00",
            "",
            "21.95",
            "Journey continuation",
        ],
        ["06-Apr-2024", "01:44", "", "Bus journey, route N5", "1.75", "", "20.20", ""],
        [
            "06-Apr-2024",
            "10:07",
            "",
            "Auto top-up",
            "",
            "15.00",
            "35.20",
            "Auto top-up",
        ],
        [
            "06-Apr-2024",
            "12:03",
            "12:21",
            "Waterloo [London Underground] to King's Cross St. Pancras [London Underground]",
            "2.70",
            "",
            "32.50",
            "",
        ],
        [
            "06-Apr-2024",
            "12:38",
            "12:53",
            "King's Cross St. Pancras [London Underground] to Baker Street [London Underground]",
            "2.40",
            "",
            "30.10",
            "",
        ],
        ["08-Apr-2024", "08:09", "", "Bus journey, route 205", "1.55", "", "28.55", ""],
        [
            "08-Apr-2024",
            "09:02",
            "09:20",
            "Baker Street [London Underground] to Holborn [London Underground]",
            "2.50",
            "",
            "26.05",
            "",
        ],
        [
            "08-Apr-2024",
            "09:34",
            "09:53",
            "Holborn [London Underground] to Canary Wharf [London Underground]",
            "2.80",
            "",
            "23.25",
            "",
        ],
        [
            "08-Apr-2024",
            "17:11",
            "",
            "Fare adjustment",
            "",
            "1.50",
            "24.75",
            "Fare adjustment",
        ],
        [
            "10-Apr-2024",
            "07:58",
            "08:17",
            "Canary Wharf [London Underground] to London Bridge [London Underground]",
            "2.60",
            "",
            "22.15",
            "",
        ],
        ["10-Apr-2024", "08:31", "", "Bus journey, route 55", "1.55", "", "20.60", ""],
        [
            "10-Apr-2024",
            "12:16",
            "12:34",
            "London Bridge [London Underground] to Green Park [London Underground]",
            "2.70",
            "",
            "17.90",
            "",
        ],
        [
            "10-Apr-2024",
            "12:49",
            "13:07",
            "Green Park [London Underground] to Paddington [London Underground]",
            "2.60",
            "",
            "15.30",
            "",
        ],
        [
            "11-Apr-2024",
            "08:12",
            "",
            "Auto top-up",
            "",
            "20.00",
            "35.30",
            "Auto top-up",
        ],
        [
            "11-Apr-2024",
            "09:05",
            "09:24",
            "Paddington (National Rail) to Liverpool Street [National Rail]",
            "0.00",
            "",
            "35.30",
            "Journey continuation",
        ],
        [
            "11-Apr-2024",
            "18:01",
            "18:16",
            "Liverpool Street [London Underground] to Bank [London Underground]",
            "2.40",
            "",
            "32.90",
            "",
        ],
        [
            "11-Apr-2024",
            "18:36",
            "18:55",
            "Bank [London Underground] to Stratford [London Underground]",
            "2.80",
            "",
            "30.10",
            "",
        ],
    ],
    "999999999_20251127.csv": [
        [
            "21-Nov-2025",
            "07:32",
            "07:50",
            "Green Park [London Underground] to Victoria [London Underground]",
            "2.40",
            "",
            "27.60",
            "",
        ],
        [
            "21-Nov-2025",
            "08:02",
            "08:18",
            "Victoria [London Underground] to Baker Street [London Underground]",
            "2.50",
            "",
            "25.10",
            "",
        ],
        [
            "21-Nov-2025",
            "17:47",
            "18:05",
            "Baker Street [London Underground] to Liverpool Street [London Underground]",
            "0.00",
            "",
            "25.10",
            "Daily cap applied",
        ],
        ["21-Nov-2025", "18:23", "", "Bus journey, route 73", "1.75", "", "23.35", ""],
        [
            "22-Nov-2025",
            "09:12",
            "09:30",
            "Liverpool Street [London Underground] to Stratford [London Underground]",
            "2.70",
            "",
            "20.65",
            "",
        ],
        ["22-Nov-2025", "10:05", "", "Fare refund", "", "2.40", "23.05", "Fare refund"],
        [
            "22-Nov-2025",
            "18:14",
            "18:31",
            "Stratford [London Underground] to Canary Wharf [London Underground]",
            "2.60",
            "",
            "20.45",
            "",
        ],
        ["22-Nov-2025", "23:41", "", "Bus journey, route N63", "1.75", "", "18.70", ""],
        [
            "24-Nov-2025",
            "07:48",
            "08:07",
            "Canary Wharf [London Underground] to London Bridge [London Underground]",
            "2.60",
            "",
            "16.10",
            "",
        ],
        [
            "24-Nov-2025",
            "08:21",
            "",
            "Auto top-up",
            "",
            "20.00",
            "36.10",
            "Auto top-up",
        ],
        [
            "24-Nov-2025",
            "12:12",
            "12:31",
            "London Bridge [London Underground] to Waterloo [London Underground]",
            "2.50",
            "",
            "33.60",
            "",
        ],
        ["24-Nov-2025", "12:49", "", "Bus journey, route 168", "1.55", "", "32.05", ""],
        [
            "26-Nov-2025",
            "07:56",
            "08:14",
            "Waterloo [London Underground] to Holborn [London Underground]",
            "2.50",
            "",
            "29.55",
            "",
        ],
        [
            "26-Nov-2025",
            "08:28",
            "08:42",
            "Holborn [London Underground] to Tottenham Court Road [London Underground]",
            "0.00",
            "",
            "29.55",
            "Journey continuation",
        ],
        [
            "26-Nov-2025",
            "17:22",
            "17:40",
            "Tottenham Court Road [London Underground] to King's Cross St. Pancras [London Underground]",
            "2.60",
            "",
            "26.95",
            "",
        ],
        [
            "26-Nov-2025",
            "17:59",
            "18:14",
            "King's Cross St. Pancras [London Underground] to Euston [London Underground]",
            "2.40",
            "",
            "24.55",
            "",
        ],
        [
            "27-Nov-2025",
            "08:06",
            "",
            "Fare adjustment",
            "",
            "1.10",
            "25.65",
            "Fare adjustment",
        ],
        ["27-Nov-2025", "09:02", "", "Bus journey, route 343", "1.55", "", "24.10", ""],
        [
            "27-Nov-2025",
            "18:39",
            "18:58",
            "Euston [London Underground] to South Kensington [London Underground]",
            "2.80",
            "",
            "21.30",
            "",
        ],
        [
            "27-Nov-2025",
            "19:28",
            "19:46",
            "South Kensington [London Underground] to Victoria [London Underground]",
            "2.40",
            "",
            "18.90",
            "",
        ],
    ],
}


def find_project_root() -> Path:
    script_path = Path(__file__).resolve()

    for parent in script_path.parents:
        has_python = (parent / "python").is_dir()
        has_data = (parent / "data").is_dir()
        has_config = (parent / "config").is_dir()
        if has_python and has_data and has_config:
            return parent

    raise FileNotFoundError("Could not find project root from script location.")


def write_csv_file(csv_path: Path, rows: list[list[str]]) -> None:
    with csv_path.open("w", newline="", encoding="utf-8") as csv_file:
        writer = csv.writer(csv_file)
        writer.writerow(CSV_HEADER)
        writer.writerows(rows)


def main() -> None:
    project_root = find_project_root()
    sample_folder = project_root / "data" / "sample" / "oyster_journey"
    sample_folder.mkdir(parents=True, exist_ok=True)

    total_row_count = 0

    for file_name, rows in SAMPLE_FILES.items():
        csv_path = sample_folder / file_name
        write_csv_file(csv_path, rows)
        total_row_count += len(rows)
        print(f"Wrote {csv_path.relative_to(project_root)} with {len(rows)} rows")

    print(f"Total sample rows written: {total_row_count}")


if __name__ == "__main__":
    main()
